go run . --color=red "hello world"
go run . --color=green "1 + 1 = 2"
go run . --color=yellow "(%&) ??"
go run . --color=orange GuYs "HeY GuYs"
go run . --color=blue B 'RGB()'
go run . --color=rainbow "hello world"
go run . --color=cyan "hello world"
go run . --color=magenta "hello world"
go run . --color=black "hello world"
go run . --color="rgb(255, 59, 244)" "hello world"
go run . --color="rgb(111, 218, 13)" "hello world"
go run . --color=#ff0000 "hello world"
go run . --color=#1B3B6F "hello world"
go run . --color=#9EB3C2 "hello world"